### ISSUE TITLE
Stopping continuous background executions

### ISSUE THREAD

**Issue by jkelowitt** [alfiopuglisi/guietta#32]
I'm trying to write a gui with a function similar to the one below. 
```python 
from guietta import Gui
import time

gui = Gui(
    [["Start"]],
    [["Stop"] ],
    ["Result" ]
    )

def count(*args):
    i = 0
    while True:
        gui.Result = i
        i += 1
        time.sleep(1)

def start_counting(*args):
    gui.execute_in_background(func=count)

def stop_counting(*args):
    pass

gui.Start = start_counting
gui.Stop = stop_counting

gui.run()
```
This function just counts the number of seconds since the "Start" button was pressed. This function will continue till it halted by an outside source. Is there some function which can halt the background execution of the count function without halting the entire program?

**Comment by alfiopuglisi** [comment]
Since the background execution happens in a thread, the simplest way is to use a global variable that is checked inside the loop, and set by the stop_counting() function.
Rather than cluttering the global namespace, you can set an attribute of the `gui` object, which will be visible everywhere. Even better, guietta defines a `gui.userdata` namespace (an instance of `SimpleNamespace`), that can be used for global data:

 
```
from guietta import Gui
import time

gui = Gui(
    [["Start"]],
    [["Stop"] ],
    ["Result" ]
    )

def count(*args):
    gui.userdata.stop = False
    i = 0
    while not gui.userdata.stop:
        gui.Result = i
        i += 1
        time.sleep(1)

def stop_counting(*args):
    gui.userdata.stop = True

def start_counting(*args):
    gui.execute_in_background(func=count)

gui.Start = start_counting
gui.Stop = stop_counting

gui.run()

```

**Comment by jkelowitt** [comment]
Wow that works perfectly. Thank you!
